title: Elementals
description: >-
  These story is about a boy named Jay and his friend how can control all four
  elements.Jay must fight his nation and fight the evil wizard who is willing
  take over the world
template:
  repo: elementals-template
  name: elementals
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
